insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Genna Orrah', 'Housekeeper', '11/15/2016', 'Female', '807-85-8423', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rossy Freckelton', 'Receptionist', '8/12/2021', 'Male', '747-80-7190', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Grantham Chainey', 'Chef', '11/8/2018', 'Male', '136-97-9710', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sydelle Farny', 'Manager', '11/28/2019', 'Female', '296-54-1200', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Allyn Bercevelo', 'Billing', '7/16/2016', 'Male', '695-93-7116', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Benoite Kinnaird', 'Receptionist', '3/1/2025', 'Female', '769-90-0929', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jane O''Hannen', 'Hotel Manager', '4/6/2016', 'Female', '376-12-4679', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nertie Waggett', 'Chef', '4/11/2022', 'Female', '783-68-2435', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lizzy Beed', 'Housekeeper', '12/29/2018', 'Female', '563-30-5981', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cody McAdam', 'Manager', '9/26/2017', 'Male', '188-94-3905', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Arlan Heathcott', 'Manager', '11/24/2015', 'Male', '845-96-8387', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bax Alecock', 'Hotel Manager', '5/22/2018', 'Male', '856-74-8999', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Leandra Quadrio', 'Security', '3/25/2025', 'Female', '413-47-5542', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Doy Tuxell', 'Billing', '10/28/2015', 'Male', '432-94-0863', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Carlye Lohrensen', 'Receptionist', '6/11/2025', 'Female', '615-82-7692', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Herby Antao', 'Chef', '4/4/2015', 'Male', '845-62-5015', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Juanita Ciccotto', 'Housekeeper', '5/16/2022', 'Female', '225-75-5711', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Seka Birth', 'Hotel Manager', '7/6/2018', 'Female', '858-35-4443', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Flori Dartnall', 'Hotel Manager', '4/2/2018', 'Female', '125-60-2564', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Deerdre Feathers', 'Billing', '5/3/2020', 'Female', '323-17-5831', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lucian Szanto', 'Security', '2/1/2017', 'Male', '844-61-0021', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lorant Cousins', 'Billing', '10/20/2015', 'Male', '306-29-2160', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Edin Ortzen', 'Billing', '6/13/2021', 'Female', '517-26-9406', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Eartha Pittwood', 'Billing', '2/28/2021', 'Female', '114-18-0446', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Abdel McLorinan', 'Chef', '7/7/2020', 'Male', '214-75-1031', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bat Twinn', 'Security', '4/23/2017', 'Male', '126-11-9658', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sebastian Tumber', 'Housekeeper', '4/6/2023', 'Male', '751-56-6949', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Filmer Kimbley', 'Housekeeper', '11/28/2022', 'Male', '822-90-4365', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Madlen Averill', 'Chef', '12/13/2018', 'Female', '129-21-5412', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Adrea Gilsthorpe', 'Hotel Manager', '6/11/2024', 'Female', '626-23-4286', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ayn Beddon', 'Manager', '4/2/2016', 'Female', '290-28-2654', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Asher Fettiplace', 'Hotel Manager', '8/13/2023', 'Male', '167-16-8484', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Baryram Hartle', 'Security', '4/25/2020', 'Male', '589-95-4343', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Parsifal Fallows', 'Security', '7/21/2018', 'Male', '333-79-4716', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Maia Jackett', 'Hotel Manager', '10/17/2016', 'Female', '678-57-6044', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Roseanne Koppelmann', 'Receptionist', '9/15/2022', 'Female', '851-89-6289', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Abra Aspinell', 'Security', '5/2/2022', 'Female', '457-52-0089', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Theodore Lockie', 'Manager', '6/6/2024', 'Male', '543-85-5958', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lynnelle Ffoulkes', 'Security', '1/13/2022', 'Female', '370-89-5778', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Egon Glass', 'Manager', '4/19/2023', 'Male', '428-75-1945', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ludwig Fattore', 'Chef', '1/29/2018', 'Male', '184-67-0397', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jecho Bagnall', 'Housekeeper', '5/2/2019', 'Male', '871-60-1962', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Gradey Holdin', 'Housekeeper', '8/27/2025', 'Male', '176-91-0341', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Viole Harg', 'Receptionist', '1/22/2026', 'Female', '457-37-3956', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Danica Hugland', 'Chef', '4/27/2016', 'Female', '850-74-6828', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Valeda Haggerwood', 'Housekeeper', '7/12/2017', 'Female', '733-13-2856', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bernadina Tustin', 'Housekeeper', '10/27/2017', 'Female', '658-98-6296', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Marya Wiggin', 'Hotel Manager', '4/11/2016', 'Female', '679-26-0368', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Norri Strettell', 'Manager', '7/30/2015', 'Female', '779-73-7997', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Mireielle Hurdedge', 'Housekeeper', '3/17/2019', 'Female', '824-46-5501', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Leesa Tyhurst', 'Billing', '10/29/2017', 'Female', '798-34-6671', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Brenda Giffon', 'Housekeeper', '8/9/2023', 'Female', '881-13-8469', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Billi Freddi', 'Billing', '5/29/2020', 'Female', '868-53-3087', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lulita Keightley', 'Receptionist', '12/12/2021', 'Female', '831-54-2467', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Theresina Bulstrode', 'Security', '3/19/2023', 'Female', '716-69-4761', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lizabeth Silkstone', 'Receptionist', '8/2/2022', 'Female', '799-29-4763', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Martino Ends', 'Receptionist', '7/29/2017', 'Male', '701-37-5266', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Leora Wallbrook', 'Billing', '10/21/2019', 'Female', '171-24-1373', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rikki Gumbley', 'Manager', '11/16/2024', 'Male', '459-74-6106', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sheffield Durman', 'Chef', '6/29/2022', 'Male', '397-10-6126', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dulcea Letcher', 'Manager', '10/17/2017', 'Female', '893-38-8269', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Donetta Hickenbottom', 'Manager', '5/31/2019', 'Female', '532-05-4831', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kassey Camerana', 'Receptionist', '5/14/2017', 'Female', '822-99-5751', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Salmon Hauxwell', 'Hotel Manager', '5/22/2019', 'Male', '581-06-4624', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dominick Garrelts', 'Hotel Manager', '9/23/2017', 'Male', '545-68-3915', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Logan Doudney', 'Housekeeper', '8/30/2017', 'Male', '665-55-5370', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Orren Lafflina', 'Chef', '11/7/2022', 'Male', '275-71-7812', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Marena Sidey', 'Chef', '12/7/2016', 'Female', '679-51-0503', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Paddie Covendon', 'Security', '8/21/2017', 'Male', '503-37-7448', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dani Labdon', 'Billing', '10/3/2016', 'Male', '892-02-0259', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Wayne Pegram', 'Housekeeper', '3/5/2015', 'Male', '330-72-5781', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tansy Margett', 'Security', '8/3/2021', 'Female', '802-26-3330', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Brent Stronach', 'Billing', '8/1/2022', 'Male', '836-71-7835', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ailyn Hatley', 'Billing', '11/1/2017', 'Female', '283-07-0700', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bartolemo Pennetti', 'Billing', '5/9/2020', 'Male', '615-71-3241', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bertha Netti', 'Receptionist', '11/11/2025', 'Female', '733-24-8571', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ferris Polet', 'Chef', '8/25/2017', 'Male', '619-52-1706', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Domenic Bever', 'Hotel Manager', '7/24/2017', 'Male', '696-89-0329', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cristina Petruk', 'Security', '3/12/2020', 'Female', '753-58-1121', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Merwyn Giacomozzo', 'Housekeeper', '12/3/2023', 'Male', '633-01-7540', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Irvin Ferrarini', 'Receptionist', '2/26/2025', 'Male', '199-80-2872', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Francklin Cornier', 'Housekeeper', '9/18/2018', 'Male', '198-06-2872', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Darrell Laxton', 'Receptionist', '2/16/2022', 'Male', '639-15-5949', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Claudette Allday', 'Billing', '8/8/2015', 'Female', '638-11-0617', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jen Eagland', 'Chef', '6/17/2025', 'Female', '764-59-4305', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Maisie Caisley', 'Billing', '9/12/2019', 'Female', '156-12-6009', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Allister Standrin', 'Chef', '7/2/2023', 'Male', '776-89-6777', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cosmo Hackley', 'Chef', '1/8/2022', 'Male', '683-17-2918', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Shani Harbard', 'Security', '8/29/2016', 'Female', '429-75-1424', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kahaleel Nance', 'Billing', '3/14/2019', 'Male', '473-36-2037', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Teri Preddy', 'Chef', '11/24/2018', 'Female', '298-24-1800', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Corly Santos', 'Chef', '2/22/2021', 'Female', '855-50-3328', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Wallis Snalom', 'Receptionist', '6/5/2018', 'Male', '375-74-6856', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Flynn Derwin', 'Manager', '8/11/2025', 'Male', '704-77-8226', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Yetty Hearnes', 'Chef', '4/21/2016', 'Female', '482-26-0905', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Luci Crecy', 'Chef', '12/4/2016', 'Female', '767-19-4388', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Margaretha Gilling', 'Billing', '1/28/2024', 'Female', '347-69-9345', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ingeberg Cuttings', 'Security', '9/20/2023', 'Female', '592-63-6432', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Arturo Tippler', 'Billing', '12/23/2019', 'Male', '775-77-6697', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jenine Cossum', 'Security', '9/6/2024', 'Female', '847-52-0555', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Wendall Foley', 'Housekeeper', '5/31/2020', 'Male', '306-94-2861', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jacki Caroll', 'Receptionist', '8/12/2018', 'Female', '123-66-5715', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Justin Tew', 'Chef', '12/16/2024', 'Male', '393-90-0842', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Clayson Roughley', 'Manager', '11/11/2018', 'Male', '643-53-5442', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('David Curl', 'Hotel Manager', '4/30/2017', 'Male', '892-34-0600', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Carmelle Schimek', 'Billing', '9/29/2023', 'Female', '705-83-9807', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Forbes Derobert', 'Manager', '7/17/2023', 'Male', '773-31-3741', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Daloris Terram', 'Manager', '3/27/2021', 'Female', '105-73-3897', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Vernor Overpool', 'Security', '5/14/2021', 'Male', '337-39-1250', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Vivianna Boxall', 'Hotel Manager', '1/17/2025', 'Female', '480-11-1975', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ethan Kuschek', 'Security', '6/9/2025', 'Male', '738-53-5480', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ambrose Bellocht', 'Receptionist', '7/6/2015', 'Male', '835-01-1943', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Katya Bradberry', 'Manager', '11/22/2015', 'Female', '537-80-8029', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Demetrius Avramovich', 'Security', '2/29/2020', 'Male', '110-52-9171', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Keefer Larham', 'Receptionist', '5/1/2023', 'Male', '115-89-4895', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Boris Sleath', 'Billing', '7/16/2024', 'Male', '667-28-2364', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Elspeth Walpole', 'Security', '5/1/2020', 'Female', '866-75-8299', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Allayne Hawking', 'Housekeeper', '9/7/2019', 'Male', '302-25-4870', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hayden Geale', 'Manager', '11/3/2021', 'Male', '810-82-6024', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sargent Howsego', 'Security', '6/19/2017', 'Male', '568-61-7030', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kort Egre', 'Chef', '6/13/2017', 'Male', '820-48-4914', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Francoise Ofield', 'Billing', '10/30/2016', 'Female', '125-54-2515', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Aubrie Garcia', 'Housekeeper', '4/3/2025', 'Female', '118-30-7755', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rey Jestico', 'Billing', '10/9/2017', 'Female', '707-76-6292', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Pincus Jiricka', 'Hotel Manager', '11/23/2019', 'Male', '536-91-4546', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ashley Jearum', 'Hotel Manager', '9/30/2022', 'Male', '562-06-7592', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Portie Attwell', 'Billing', '6/27/2025', 'Male', '487-70-5105', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Paxton Burdekin', 'Housekeeper', '2/12/2025', 'Male', '822-75-4217', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Renelle Romeril', 'Hotel Manager', '7/21/2020', 'Female', '874-88-4197', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lettie Loyd', 'Billing', '7/14/2021', 'Female', '712-95-6683', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Eugine Hoyes', 'Manager', '11/30/2016', 'Female', '410-32-3898', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hamlin Wahner', 'Hotel Manager', '1/13/2024', 'Male', '319-40-6845', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Peg Ecclestone', 'Manager', '9/15/2018', 'Female', '525-96-0045', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Englebert Browell', 'Chef', '9/2/2023', 'Male', '803-07-0048', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Orazio Elldred', 'Security', '4/26/2018', 'Male', '718-45-7509', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nadya Gullen', 'Billing', '5/19/2020', 'Female', '355-29-2762', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Roldan Silcocks', 'Receptionist', '9/9/2019', 'Male', '348-59-7211', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Keefe Redborn', 'Billing', '9/3/2022', 'Male', '344-79-8192', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Trace Ramstead', 'Manager', '2/22/2023', 'Male', '421-34-4933', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Giovanna Druitt', 'Security', '3/17/2023', 'Female', '252-32-1576', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Phillipe Fuller', 'Hotel Manager', '1/16/2018', 'Male', '231-55-7601', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jessey Capelle', 'Security', '5/24/2018', 'Male', '208-94-0123', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('York Annand', 'Receptionist', '7/25/2023', 'Male', '362-68-9334', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Byron Le Gallo', 'Housekeeper', '3/4/2025', 'Male', '371-06-7018', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Fanchette Coad', 'Receptionist', '5/17/2016', 'Female', '677-69-6257', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rose Chiswell', 'Security', '8/30/2020', 'Female', '257-20-3103', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Vinita Woffenden', 'Security', '11/9/2022', 'Female', '214-54-9273', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Zonda Tomeo', 'Receptionist', '1/8/2017', 'Female', '837-23-1424', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kippie Gazzard', 'Manager', '11/3/2017', 'Male', '772-79-7431', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sean McQuode', 'Housekeeper', '11/5/2025', 'Male', '743-43-9962', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sissie Tolworthie', 'Manager', '8/11/2021', 'Female', '480-81-6813', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cobbie Kapiloff', 'Billing', '9/24/2021', 'Male', '569-26-0734', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Neron Gutowska', 'Security', '9/10/2025', 'Male', '303-57-9301', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Yorgo Negro', 'Billing', '3/16/2015', 'Male', '514-30-5709', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Orion Ruseworth', 'Billing', '8/18/2021', 'Male', '455-50-6442', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Geneva Drewet', 'Hotel Manager', '1/11/2026', 'Female', '341-30-5950', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Claudia Ortet', 'Manager', '5/18/2020', 'Female', '848-24-0573', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tarrance Marklew', 'Manager', '1/15/2026', 'Male', '404-06-0940', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Berne Howlin', 'Receptionist', '2/26/2020', 'Male', '153-46-8263', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Mirelle Ponting', 'Billing', '1/1/2021', 'Female', '711-84-3450', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Deonne Cornwall', 'Chef', '1/26/2026', 'Female', '599-70-3353', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jamison Serris', 'Housekeeper', '9/14/2023', 'Male', '250-91-8956', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Maribelle Callinan', 'Housekeeper', '10/23/2023', 'Female', '721-69-2091', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cleo Pounds', 'Billing', '8/8/2017', 'Female', '653-85-3188', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Reggie Franzewitch', 'Hotel Manager', '7/30/2023', 'Female', '525-12-7658', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bree Aberdein', 'Hotel Manager', '4/10/2025', 'Female', '139-31-1922', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Eberhard Casaro', 'Receptionist', '1/30/2023', 'Male', '232-97-3859', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Colver O'' Reagan', 'Housekeeper', '9/14/2021', 'Male', '797-38-6482', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Noby Sandifer', 'Security', '4/4/2016', 'Male', '404-31-3945', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Aleece Dominguez', 'Billing', '11/12/2015', 'Female', '295-18-8004', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Edsel Bessom', 'Receptionist', '10/31/2018', 'Male', '387-35-6241', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Alexi Styant', 'Chef', '6/16/2017', 'Female', '201-24-2809', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Keely Ollie', 'Security', '3/23/2017', 'Female', '684-72-9722', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Andria Jecock', 'Receptionist', '3/7/2023', 'Female', '489-98-9660', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Graehme Bertomieu', 'Billing', '8/7/2022', 'Male', '885-85-7448', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Christoper Heskins', 'Hotel Manager', '2/5/2021', 'Male', '857-58-6896', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Fayina Keasy', 'Housekeeper', '8/23/2023', 'Female', '349-78-0732', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Holden Ingrey', 'Security', '3/12/2018', 'Male', '253-28-2992', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Babara Keave', 'Hotel Manager', '12/28/2019', 'Female', '477-38-5275', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Aretha De Morena', 'Receptionist', '7/5/2024', 'Female', '427-49-8482', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Louise Saice', 'Billing', '7/14/2023', 'Female', '813-94-8579', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Luigi Whistlecraft', 'Security', '3/13/2025', 'Male', '159-77-9325', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ludwig Booth-Jarvis', 'Receptionist', '11/14/2025', 'Male', '204-29-2569', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dodie Record', 'Billing', '12/3/2021', 'Female', '864-27-3010', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Winne Hayman', 'Hotel Manager', '4/11/2016', 'Female', '275-49-1746', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Isabella Seares', 'Hotel Manager', '11/12/2024', 'Female', '264-84-6316', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Austine Haborn', 'Chef', '3/8/2016', 'Female', '210-29-9901', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hammad Langtree', 'Billing', '11/9/2024', 'Male', '814-25-8309', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Melisent Paullin', 'Housekeeper', '5/22/2016', 'Female', '375-11-6227', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Garvey Gawkes', 'Receptionist', '9/11/2019', 'Male', '396-26-4239', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Theresina Margerison', 'Billing', '5/26/2020', 'Female', '737-50-7799', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Clifford Kemster', 'Manager', '7/1/2024', 'Male', '275-33-0760', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Irving Pinckstone', 'Billing', '10/28/2024', 'Male', '303-66-8730', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ogden Tschirasche', 'Manager', '10/16/2021', 'Male', '827-05-3488', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Allen Rieger', 'Billing', '4/10/2020', 'Male', '439-92-6773', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Isidoro Marlin', 'Billing', '7/10/2020', 'Male', '724-41-2638', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ozzy Monteath', 'Security', '7/27/2023', 'Male', '165-84-8239', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Deane Cubbino', 'Housekeeper', '1/15/2023', 'Female', '159-05-0579', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Garvy Gemnett', 'Hotel Manager', '8/29/2016', 'Male', '177-32-5543', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Fanchon Simmank', 'Manager', '1/13/2019', 'Female', '108-76-5338', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Carny Vogeler', 'Receptionist', '9/14/2015', 'Male', '556-38-8439', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Efrem Pamment', 'Receptionist', '8/28/2017', 'Male', '832-34-3925', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Meridith Abatelli', 'Housekeeper', '4/24/2018', 'Female', '817-47-8748', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Emmey Redfield', 'Billing', '9/4/2016', 'Female', '690-49-4070', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Florina Fagge', 'Security', '1/26/2016', 'Female', '191-96-8594', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Eugenia Bensley', 'Chef', '5/25/2017', 'Female', '530-51-6040', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hube Bryant', 'Housekeeper', '11/15/2016', 'Male', '292-58-1930', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Niel Gobat', 'Security', '9/15/2021', 'Male', '705-41-7243', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ely Comello', 'Chef', '3/2/2016', 'Male', '770-84-9859', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hendrika Glascott', 'Chef', '7/11/2023', 'Female', '257-47-8058', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cyrille Ardron', 'Chef', '12/27/2018', 'Male', '708-67-4402', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Evelyn Windham', 'Hotel Manager', '7/19/2022', 'Male', '123-07-1426', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Vina Musico', 'Manager', '8/9/2020', 'Female', '537-80-0887', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Marcel Rappaport', 'Billing', '3/25/2017', 'Male', '728-07-9068', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Neall Roarty', 'Manager', '8/14/2015', 'Male', '765-82-7992', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Skell Gerlack', 'Hotel Manager', '7/6/2024', 'Male', '376-37-8532', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Andreas Stolle', 'Security', '5/30/2017', 'Male', '181-97-9368', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sammy Baumler', 'Manager', '2/17/2021', 'Male', '488-71-6063', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lou Stables', 'Billing', '11/1/2017', 'Female', '543-53-8536', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Vivyanne Enrique', 'Security', '7/11/2023', 'Female', '540-56-3430', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sandy Brockton', 'Manager', '2/26/2017', 'Male', '228-24-0023', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sax Skivington', 'Manager', '9/8/2024', 'Male', '712-35-3966', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rogerio Maudlen', 'Security', '1/12/2021', 'Male', '886-61-4286', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Yetty Gammade', 'Housekeeper', '3/30/2021', 'Female', '786-05-8243', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Edi Brand', 'Billing', '7/3/2025', 'Female', '561-20-6534', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sansone Wayland', 'Manager', '4/18/2017', 'Male', '308-08-5117', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Harwell Keyzor', 'Hotel Manager', '9/8/2019', 'Male', '450-82-3691', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dulciana Dickons', 'Receptionist', '8/17/2017', 'Female', '224-25-5350', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nikoletta Lope', 'Hotel Manager', '3/17/2015', 'Female', '859-16-1026', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Guillaume Kettel', 'Manager', '8/12/2021', 'Male', '866-33-9653', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Clarence Bubb', 'Security', '10/15/2018', 'Male', '823-78-9779', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Gabriel Matthiesen', 'Housekeeper', '3/26/2019', 'Female', '689-57-3856', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sonni Ricciardo', 'Receptionist', '6/28/2023', 'Female', '233-77-8362', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lurlene Colbourn', 'Chef', '8/13/2016', 'Female', '307-48-7875', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Skyler Deaconson', 'Manager', '10/13/2015', 'Male', '134-33-3356', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hollie O''Shesnan', 'Housekeeper', '12/16/2018', 'Female', '359-36-0822', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Maurizio Harsent', 'Manager', '4/14/2020', 'Male', '852-07-3067', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jay Axford', 'Hotel Manager', '6/5/2016', 'Male', '404-52-5636', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rasia Hinkens', 'Manager', '1/19/2020', 'Female', '709-60-2889', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cynthia Normabell', 'Housekeeper', '10/14/2016', 'Female', '177-28-5697', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Casper Shipley', 'Chef', '4/27/2020', 'Male', '781-70-3052', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Zerk Harcus', 'Housekeeper', '12/19/2025', 'Male', '234-66-4215', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Obidiah Ehlerding', 'Hotel Manager', '2/14/2023', 'Male', '262-95-6501', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bernie McGilleghole', 'Chef', '1/11/2024', 'Female', '805-60-5477', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lin Collinge', 'Manager', '10/1/2015', 'Female', '493-65-8451', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kati Ruck', 'Chef', '11/3/2023', 'Female', '445-85-8743', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Adamo Fundell', 'Security', '4/26/2018', 'Male', '878-14-0354', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Alexa Dorracott', 'Manager', '4/20/2019', 'Female', '595-55-1336', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rafaellle Elington', 'Hotel Manager', '12/21/2022', 'Male', '208-26-4926', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Janina Berick', 'Housekeeper', '2/22/2016', 'Female', '539-54-5530', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Mellicent Junkin', 'Security', '7/9/2021', 'Female', '723-04-1447', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tarrance Eslinger', 'Chef', '9/14/2022', 'Male', '284-96-3133', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ermina Potten', 'Housekeeper', '11/2/2024', 'Female', '223-31-8549', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jamaal Jansema', 'Housekeeper', '6/21/2018', 'Male', '274-16-0642', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Eolande Ellson', 'Receptionist', '7/6/2023', 'Female', '577-82-7650', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Anne-marie Strahan', 'Housekeeper', '10/13/2025', 'Female', '755-09-5778', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Brenda Galland', 'Manager', '10/15/2015', 'Female', '483-66-6847', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Genevra Gipson', 'Security', '10/11/2020', 'Female', '743-56-6877', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Wallie Mawby', 'Receptionist', '6/9/2016', 'Male', '670-01-0321', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Chic Easdon', 'Chef', '4/20/2020', 'Male', '412-32-7372', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Annalise Mulqueen', 'Housekeeper', '6/16/2024', 'Female', '857-43-6865', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tobiah Niblock', 'Receptionist', '8/26/2023', 'Male', '672-36-7074', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Klara Marin', 'Chef', '1/12/2019', 'Female', '887-60-5227', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sherlock Goslin', 'Chef', '3/12/2017', 'Male', '529-90-6585', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Richie Jannings', 'Housekeeper', '3/5/2016', 'Male', '440-51-8106', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Blondell Glozman', 'Receptionist', '6/27/2022', 'Female', '244-38-1413', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Biddy Hackford', 'Chef', '9/18/2023', 'Female', '364-75-8348', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Alexandro Bicknell', 'Manager', '4/22/2021', 'Male', '445-23-7601', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Venus Livzey', 'Hotel Manager', '7/10/2015', 'Female', '704-19-1276', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Melamie Goymer', 'Billing', '9/28/2024', 'Female', '686-14-0765', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hewie McNalley', 'Receptionist', '2/15/2026', 'Male', '523-65-8124', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Janaye Tincey', 'Receptionist', '8/13/2018', 'Female', '858-61-0708', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Clair Nibloe', 'Security', '8/10/2023', 'Female', '157-06-5613', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Danita Bartczak', 'Chef', '3/2/2015', 'Female', '130-32-0219', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Brandyn Elnaugh', 'Security', '1/3/2016', 'Male', '899-08-7065', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Gretal Petken', 'Security', '8/3/2025', 'Female', '258-50-2220', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Berrie Tunmore', 'Billing', '4/26/2017', 'Female', '271-27-7251', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Christiane Zoellner', 'Security', '6/26/2022', 'Female', '198-87-8140', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Daren Hentzer', 'Manager', '11/17/2023', 'Male', '765-43-1172', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Chrissie Childerley', 'Manager', '8/17/2024', 'Female', '816-45-5154', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cora Chell', 'Chef', '10/17/2022', 'Female', '550-70-4240', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('King Malinson', 'Billing', '8/25/2024', 'Male', '510-71-9122', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Blair Brockie', 'Receptionist', '12/9/2018', 'Male', '662-18-6381', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Carmella Timson', 'Receptionist', '9/19/2025', 'Female', '108-44-9152', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Reilly Stainer', 'Billing', '4/27/2018', 'Male', '403-37-6433', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tadd Izard', 'Billing', '1/7/2017', 'Male', '482-19-8168', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ketty Macklin', 'Hotel Manager', '3/17/2019', 'Female', '310-12-5521', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Darline Ikin', 'Security', '4/19/2022', 'Female', '427-83-4536', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Patrick Mazzei', 'Housekeeper', '3/30/2015', 'Male', '160-11-4956', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Almire Porritt', 'Hotel Manager', '10/7/2024', 'Female', '622-75-6791', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Aubrette Drakard', 'Chef', '3/13/2023', 'Female', '442-89-9401', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hillyer Dory', 'Housekeeper', '3/13/2020', 'Male', '494-97-6559', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Falito Lasham', 'Hotel Manager', '8/20/2023', 'Male', '397-97-8134', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kinsley Drillingcourt', 'Hotel Manager', '10/5/2021', 'Male', '683-52-0282', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Connor Seabrocke', 'Hotel Manager', '3/25/2018', 'Male', '424-88-6453', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Wheeler Dyson', 'Manager', '12/17/2022', 'Male', '690-65-8733', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dietrich Thatcham', 'Hotel Manager', '3/2/2021', 'Male', '449-11-0103', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Edgar Vokins', 'Chef', '6/2/2023', 'Male', '339-10-2034', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Derwin Ludlamme', 'Housekeeper', '3/31/2019', 'Male', '495-73-9468', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Olenka Rymell', 'Receptionist', '6/22/2019', 'Female', '769-41-4214', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Etienne Pheasant', 'Housekeeper', '10/17/2025', 'Male', '169-82-5320', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rivkah Mc Caughan', 'Manager', '6/30/2015', 'Female', '242-54-4459', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tomaso Laherty', 'Manager', '11/28/2022', 'Male', '270-88-5008', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Barton Cathcart', 'Housekeeper', '9/27/2015', 'Male', '158-24-7371', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Karon Pabel', 'Receptionist', '1/24/2016', 'Female', '308-22-7470', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sherlock Dennidge', 'Billing', '7/25/2023', 'Male', '600-64-8193', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Berty Marham', 'Manager', '5/29/2025', 'Female', '816-50-0424', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Maire Nutkin', 'Billing', '3/5/2023', 'Female', '196-40-9535', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bruis Bouette', 'Manager', '12/22/2025', 'Male', '357-35-5981', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tomkin Margaret', 'Housekeeper', '8/29/2025', 'Male', '893-67-0064', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jecho Milligan', 'Chef', '1/31/2020', 'Male', '163-74-1733', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Blancha Pevsner', 'Chef', '2/17/2024', 'Female', '211-37-6260', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Reese Maplesden', 'Billing', '12/20/2016', 'Male', '275-42-1940', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Devi Oxford', 'Housekeeper', '2/20/2026', 'Female', '564-04-8515', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Anneliese Pudge', 'Billing', '2/28/2021', 'Female', '151-11-2612', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Saloma Ryles', 'Billing', '1/17/2020', 'Female', '734-08-1114', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Stephanus Tedstone', 'Security', '6/22/2017', 'Male', '485-75-4462', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dodi Swadlen', 'Receptionist', '2/21/2026', 'Female', '347-28-8743', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Torrence Cheales', 'Receptionist', '3/26/2025', 'Male', '822-54-6018', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Augustin Rizzini', 'Billing', '9/6/2023', 'Male', '593-41-9114', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ingmar Tonry', 'Security', '7/9/2025', 'Male', '536-29-8694', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Douglass Leijs', 'Receptionist', '10/19/2017', 'Male', '740-53-7160', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tracy Stratten', 'Receptionist', '10/27/2015', 'Male', '674-78-5363', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Justis Neasam', 'Manager', '4/13/2025', 'Male', '243-56-2239', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Marybelle McWhannel', 'Billing', '10/21/2023', 'Female', '143-96-9967', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Maxie Shurrock', 'Hotel Manager', '11/29/2016', 'Male', '333-06-9047', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Melodee Heathorn', 'Chef', '3/9/2024', 'Female', '803-17-1695', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Warde Gingell', 'Receptionist', '7/29/2015', 'Male', '396-52-6750', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Reed Monelli', 'Receptionist', '7/22/2022', 'Male', '244-35-1588', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nada Ziems', 'Billing', '2/28/2024', 'Female', '173-87-5415', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Udale Crilly', 'Chef', '7/3/2018', 'Male', '409-14-0027', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Damita Kinghorne', 'Housekeeper', '11/13/2016', 'Female', '889-13-9679', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Genovera Mozzi', 'Housekeeper', '1/21/2021', 'Female', '404-18-4550', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hanny Goscomb', 'Receptionist', '3/19/2019', 'Female', '664-12-9458', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lissi Marquese', 'Receptionist', '7/9/2023', 'Female', '142-05-1122', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Keenan Maxted', 'Chef', '3/11/2017', 'Male', '804-97-4165', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Joelynn Ure', 'Hotel Manager', '5/28/2025', 'Female', '640-19-1887', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ezechiel Crowdy', 'Security', '4/14/2019', 'Male', '149-09-3518', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kelila Pellew', 'Security', '11/12/2017', 'Female', '288-72-2475', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sibelle Bree', 'Receptionist', '8/3/2015', 'Female', '409-40-3019', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rahel Sandwith', 'Chef', '9/21/2024', 'Female', '227-54-6937', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tamera Glasard', 'Chef', '5/19/2021', 'Female', '633-19-3084', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Torrence Sharple', 'Housekeeper', '7/4/2021', 'Male', '675-39-7818', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jozef Onion', 'Housekeeper', '4/20/2024', 'Male', '265-21-5663', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kristen Prosh', 'Hotel Manager', '8/20/2022', 'Female', '891-21-0652', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rosalynd Claige', 'Billing', '6/10/2017', 'Female', '776-30-3354', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Corina Charrett', 'Receptionist', '2/20/2018', 'Female', '525-23-9858', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Fair Westcar', 'Housekeeper', '4/25/2016', 'Male', '277-72-1351', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bartholomeo Walklett', 'Chef', '10/25/2024', 'Male', '732-34-6213', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Karee Kennifick', 'Chef', '3/19/2024', 'Female', '187-80-0114', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sawyere Affleck', 'Manager', '12/7/2025', 'Male', '741-85-8601', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cristine Lydiatt', 'Receptionist', '12/12/2017', 'Female', '148-91-1674', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Stesha Gillett', 'Hotel Manager', '12/31/2017', 'Female', '624-24-0755', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Maureen Haycraft', 'Housekeeper', '8/12/2023', 'Female', '394-20-7955', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nana O''Hollegan', 'Hotel Manager', '5/29/2023', 'Female', '296-53-1416', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Elva Karoly', 'Manager', '9/8/2019', 'Female', '616-40-7795', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Linnet Ingilson', 'Billing', '9/24/2022', 'Female', '894-87-1957', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Raviv Darracott', 'Receptionist', '6/22/2021', 'Male', '632-10-8913', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Zaneta Mathen', 'Security', '11/4/2017', 'Female', '600-29-6370', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Remington Kinavan', 'Security', '11/5/2019', 'Male', '532-98-8785', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Garvy Rawsthorne', 'Billing', '7/19/2020', 'Male', '565-46-0346', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Marge Pavlata', 'Chef', '5/22/2024', 'Female', '268-29-8434', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Pascal Tansley', 'Hotel Manager', '6/13/2021', 'Male', '525-11-8767', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Binny Foakes', 'Chef', '2/29/2024', 'Female', '731-98-0904', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Paulo Lambarth', 'Chef', '12/8/2017', 'Male', '263-24-4393', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Isidro St. Quintin', 'Chef', '10/10/2016', 'Male', '449-75-1013', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Bee Smallwood', 'Housekeeper', '1/3/2019', 'Female', '607-21-5850', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Leigh Hatherell', 'Housekeeper', '10/11/2015', 'Female', '349-62-0997', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Miriam O''Lunny', 'Manager', '8/31/2021', 'Female', '845-49-1496', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Randolf Ballendine', 'Receptionist', '3/17/2016', 'Male', '888-66-2998', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Elwood Rosedale', 'Manager', '10/25/2020', 'Male', '269-90-8245', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Chloris Masterson', 'Hotel Manager', '1/6/2020', 'Female', '224-65-0326', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Mufi Balden', 'Chef', '12/18/2017', 'Female', '393-79-9976', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kiersten Woodeson', 'Billing', '11/16/2025', 'Female', '636-28-0126', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hamel Hasser', 'Billing', '12/28/2021', 'Male', '582-60-4729', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kate Clemerson', 'Receptionist', '3/10/2018', 'Female', '182-77-9405', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Minda Hoggins', 'Chef', '1/21/2023', 'Female', '460-88-8557', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dionne Blackborow', 'Receptionist', '4/25/2023', 'Female', '760-92-0204', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Linda Hullin', 'Chef', '1/23/2021', 'Female', '281-58-9109', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Harmon Blakden', 'Manager', '5/23/2016', 'Male', '102-16-1666', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Darin Hassent', 'Housekeeper', '8/7/2016', 'Male', '390-38-7470', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Patrica McAllister', 'Security', '3/18/2018', 'Female', '269-52-5729', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Alonso Postians', 'Chef', '3/29/2018', 'Male', '842-54-7412', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Auroora McNamara', 'Manager', '4/13/2018', 'Female', '600-70-9357', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ada Crush', 'Security', '12/18/2015', 'Female', '394-88-1834', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ruben Tyce', 'Billing', '12/28/2016', 'Male', '332-98-6408', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Caldwell Estcourt', 'Hotel Manager', '10/10/2024', 'Male', '526-29-5840', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Guglielmo Candie', 'Chef', '6/7/2020', 'Male', '877-41-6764', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Alphonse Borghese', 'Receptionist', '6/30/2016', 'Male', '191-41-1152', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jeremiah O''Corrin', 'Security', '8/24/2018', 'Male', '492-72-1849', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jeralee Bryson', 'Receptionist', '8/25/2023', 'Female', '880-11-8438', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kerry Bonnar', 'Billing', '12/22/2024', 'Female', '189-77-6469', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Pete Blanckley', 'Manager', '12/22/2024', 'Male', '727-66-4396', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Humphrey Latimer', 'Receptionist', '12/22/2018', 'Male', '861-97-1755', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Heidi Amorine', 'Chef', '11/17/2020', 'Female', '266-19-7562', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Giacomo Tinline', 'Hotel Manager', '1/9/2023', 'Male', '297-12-8792', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Grannie Loughead', 'Housekeeper', '4/12/2015', 'Male', '124-25-2845', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Perri Najara', 'Chef', '10/20/2020', 'Female', '847-42-4263', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Marijo Gilardengo', 'Manager', '1/18/2023', 'Female', '679-60-6847', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Wheeler Remmer', 'Receptionist', '2/2/2024', 'Male', '397-44-2972', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dino Arrol', 'Housekeeper', '9/1/2015', 'Male', '710-17-0441', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Cheston Terrill', 'Hotel Manager', '8/5/2016', 'Male', '572-89-1012', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sioux Drillingcourt', 'Chef', '6/1/2018', 'Female', '592-88-3822', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tobias Leng', 'Chef', '12/13/2020', 'Male', '876-24-6879', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Carmela Franzoli', 'Chef', '8/2/2018', 'Female', '296-11-2027', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nike Jamary', 'Billing', '2/13/2025', 'Female', '382-63-8480', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Andrea Angrick', 'Security', '6/15/2024', 'Male', '609-41-5289', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Manon Bonfield', 'Receptionist', '11/12/2025', 'Female', '755-63-8177', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jude Elcom', 'Chef', '7/3/2018', 'Male', '634-89-8297', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Donelle Gover', 'Security', '10/31/2015', 'Female', '750-97-0093', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Niki Hawthorn', 'Manager', '3/26/2024', 'Male', '586-11-9621', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lazare Gniewosz', 'Manager', '9/21/2020', 'Male', '109-47-2491', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Stanfield Leban', 'Receptionist', '10/14/2020', 'Male', '302-08-3400', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nelie Basant', 'Manager', '7/26/2018', 'Female', '525-23-1862', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Andriana Beeze', 'Housekeeper', '11/7/2020', 'Female', '263-04-8610', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Charlena Latty', 'Hotel Manager', '12/10/2024', 'Female', '528-16-8951', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Janela Rivelon', 'Manager', '6/16/2019', 'Female', '144-34-7317', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jaynell Corssen', 'Chef', '2/8/2021', 'Female', '349-78-5723', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Anabelle Elie', 'Hotel Manager', '7/16/2022', 'Female', '729-42-0633', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Honor Kinker', 'Hotel Manager', '2/28/2024', 'Female', '128-23-5114', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Jermaine Dunphie', 'Billing', '12/5/2016', 'Male', '609-64-5399', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Meredith Rehorek', 'Receptionist', '10/3/2015', 'Male', '625-05-6320', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Kaine Simacek', 'Billing', '11/7/2024', 'Male', '402-64-8254', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Natalya MacFayden', 'Chef', '11/2/2023', 'Female', '426-37-2069', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Terencio Eveling', 'Chef', '7/3/2025', 'Male', '495-01-3694', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Anet Gregoriou', 'Receptionist', '1/15/2019', 'Female', '113-64-7869', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Chandra Dumberell', 'Security', '3/8/2025', 'Female', '412-36-7518', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Pieter Kinningley', 'Chef', '3/6/2018', 'Male', '858-60-1145', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Joceline Alvarado', 'Chef', '8/30/2022', 'Female', '164-47-5165', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Karlotte Bridgman', 'Chef', '7/13/2022', 'Female', '706-41-7432', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sarene Claridge', 'Manager', '2/10/2025', 'Female', '232-91-1414', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Alwyn Hibbart', 'Chef', '8/29/2020', 'Male', '497-46-9555', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rosina Treamayne', 'Security', '8/3/2017', 'Female', '383-48-4256', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Mohammed Widdicombe', 'Housekeeper', '7/11/2019', 'Male', '691-64-2401', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Skipper Waddie', 'Billing', '4/6/2024', 'Male', '509-87-2110', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Karoly Gascoine', 'Manager', '11/28/2021', 'Female', '492-59-6978', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lodovico Grennan', 'Hotel Manager', '11/14/2018', 'Male', '384-57-7708', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lulu Slight', 'Hotel Manager', '11/14/2023', 'Female', '190-52-2940', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Reinhard Skillett', 'Housekeeper', '4/2/2015', 'Male', '400-02-4186', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Calley Lapere', 'Housekeeper', '6/14/2025', 'Female', '614-76-7145', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Alika Doe', 'Hotel Manager', '2/25/2022', 'Female', '679-14-1638', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Olympie Lethcoe', 'Security', '1/22/2021', 'Female', '691-30-1135', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Zedekiah Norcross', 'Manager', '9/17/2023', 'Male', '864-28-6829', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Vanny Bouette', 'Security', '4/12/2019', 'Female', '400-40-9563', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Erich Eagers', 'Billing', '8/3/2025', 'Male', '386-34-7110', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Welch Duchant', 'Security', '2/26/2021', 'Male', '397-38-8609', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lanna Buckles', 'Manager', '12/24/2016', 'Female', '696-68-0902', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Gib Brumbie', 'Security', '2/15/2025', 'Male', '737-46-2364', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nola Lendrem', 'Receptionist', '11/12/2018', 'Female', '595-02-1279', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Victor McCreary', 'Housekeeper', '4/13/2022', 'Male', '227-67-8068', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rabi Whitley', 'Security', '12/20/2025', 'Male', '204-55-5253', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Harley Mailes', 'Chef', '10/24/2019', 'Female', '539-75-8523', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Eustacia Petrovic', 'Chef', '3/7/2021', 'Female', '531-89-9525', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Regina Leech', 'Chef', '12/19/2022', 'Female', '897-61-3499', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Franklin Philipsson', 'Billing', '1/1/2021', 'Male', '404-85-3588', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ladonna Piser', 'Receptionist', '5/4/2024', 'Female', '623-31-9495', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dane Snel', 'Hotel Manager', '5/8/2021', 'Male', '501-35-1251', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Augie Conyer', 'Hotel Manager', '6/8/2015', 'Male', '892-67-7029', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ricoriki Doughartie', 'Hotel Manager', '1/11/2022', 'Male', '421-49-2406', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dell Linne', 'Receptionist', '5/22/2019', 'Male', '637-95-0522', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Abbey Ong', 'Receptionist', '4/25/2016', 'Female', '657-57-3552', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Marco Abrahim', 'Manager', '12/25/2020', 'Male', '125-34-5340', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Eugine Haughan', 'Receptionist', '4/1/2025', 'Female', '360-82-8149', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Petunia Hylands', 'Receptionist', '9/15/2023', 'Female', '425-63-7000', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Homer Sargerson', 'Housekeeper', '12/3/2023', 'Male', '898-36-3271', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Amber Traves', 'Hotel Manager', '2/22/2018', 'Female', '709-33-0911', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ivie Lyfe', 'Manager', '9/27/2023', 'Female', '367-31-9993', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Paco Lening', 'Hotel Manager', '11/16/2016', 'Male', '149-82-1034', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Rozanne O''Doherty', 'Hotel Manager', '3/3/2022', 'Female', '121-87-4052', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Nert Ondracek', 'Security', '9/1/2022', 'Female', '366-02-7175', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Wenda Penhalewick', 'Security', '4/23/2023', 'Female', '428-29-2482', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tracy Castagnet', 'Housekeeper', '2/10/2022', 'Male', '155-30-9460', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lou Von Salzberg', 'Hotel Manager', '6/29/2015', 'Male', '346-98-0994', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Hinze Woodroofe', 'Receptionist', '10/18/2022', 'Male', '512-45-4593', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Erie Engelmann', 'Housekeeper', '8/21/2020', 'Male', '123-79-7242', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Broderic Rosenblum', 'Receptionist', '4/16/2016', 'Male', '702-09-5145', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Padget Gissop', 'Hotel Manager', '8/19/2023', 'Male', '428-09-0458', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Lacy McDougal', 'Billing', '9/30/2023', 'Female', '423-96-8599', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Charissa Bruntjen', 'Chef', '1/7/2016', 'Female', '493-18-6191', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Pall Cookman', 'Security', '10/13/2020', 'Male', '645-64-4703', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Micheal Blaskett', 'Chef', '5/16/2020', 'Male', '503-67-1190', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Yance Atyeo', 'Chef', '5/20/2015', 'Male', '501-15-1130', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Mead Pinkney', 'Receptionist', '12/4/2019', 'Female', '866-70-5366', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sawyer Pibworth', 'Manager', '12/9/2019', 'Male', '124-90-4953', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dal Tanner', 'Billing', '3/29/2024', 'Male', '673-51-3415', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dante Shute', 'Manager', '6/7/2018', 'Male', '862-13-9477', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Port Wickenden', 'Manager', '9/7/2015', 'Male', '135-71-4749', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Sally Amott', 'Security', '2/9/2017', 'Female', '241-55-6918', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Megen Chettoe', 'Chef', '7/20/2018', 'Female', '503-71-6725', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Christophe Margarson', 'Billing', '1/19/2021', 'Male', '421-43-5575', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Howey Seller', 'Security', '11/9/2015', 'Male', '723-97-7831', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Annmaria Camden', 'Chef', '12/18/2022', 'Female', '291-57-2922', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Ulick Ludman', 'Receptionist', '3/2/2022', 'Male', '356-71-1579', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Aubrey Gherarducci', 'Receptionist', '1/4/2026', 'Male', '429-28-5833', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Saleem Vynehall', 'Housekeeper', '10/15/2018', 'Male', '165-60-1967', 'Divorced');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Tessi Nutkins', 'Hotel Manager', '2/23/2017', 'Female', '802-91-8523', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Easter Cordie', 'Receptionist', '11/28/2016', 'Female', '864-39-1760', 'Single');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Dawn Pinnegar', 'Chef', '7/13/2022', 'Female', '816-42-6206', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Trefor MacKenny', 'Chef', '5/8/2019', 'Male', '430-75-6994', 'Married');
insert into Employee (EmpName, JobRole, hiring_Date, Gender, SSN, Marital_Status) values ('Adeline Bletsor', 'Manager', '12/31/2017', 'Female', '106-80-9487', 'Single');
